#:schema https://raw.githubusercontent.com/schemathesis/schemathesis/master/src/schemathesis/config/schema.json

generation.max-examples = 5
rate-limit = "5/m"
request-timeout = 10.0

[phases.stateful]
enabled = false

[phases.coverage]
unexpected-methods = []

[checks]
unsupported_method.enabled = false
negative_data_rejection.enabled = false