name: Performance Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  k6-performance-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 smoke performance test
        run: |
          k6 run performance/reqres-smoke-performance.js